# Generated by Django 3.2.3 on 2021-05-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_auto_20210520_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokeowner',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='jokeowner',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='jokeowner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
