# Generated by Django 3.2.3 on 2021-05-21 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_auto_20210521_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
